apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cifar-cnn-gitops-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/koenchill/cifar_data_classification_cnn.git
    targetRevision: dev
    path: deploy/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
