apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          env:
            - name: APP_ENV
              value: production
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "1500m"
              memory: 2Gi
